enum Languages {
  AFRIKAANS,
  ALBANIAN,
  ARABIC,
  AZERBAIJANI,
  BULGARIAN,
  CATALAN,
  CZECH,
  DANISH,
  GERMAN,
  GREEK,
  ENGLISH,
  BASQUE,
  PERSIAN_FARSI,
  FARSI,
  FINNISH,
  FRENCH,
  GALICIAN,
  HEBREW,
  HINDI,
  CROATIAN,
  HUNGARIAN,
  INDONESIAN,
  ITALIAN,
  JAPANESE,
  KOREAN,
  LATVIAN,
  LITHUANIAN,
  MACEDONIAN,
  NORWEGIAN,
  DUTCH,
  POLISH,
  PORTUGUESE,
  PORTUGUESE_BRAZIL,
  ROMANIAN,
  RUSSIAN,
  SWEDISH,
  SLOVAK,
  SLOVENIAN,
  SPANISH,
  SERBIAN,
  THAI,
  TURKISH,
  UKRAINIAN,
  VIETNAMESE,
  CHINESE_SIMPLIFIED,
  CHINESE_TRADITIONAL,
  ZULU,
}


Map<Languages, String> languageCodeString = {
  Languages.AFRIKAANS: 'af',
  Languages.ALBANIAN: 'al',
  Languages.ARABIC: 'ar',
  Languages.AZERBAIJANI: 'az',
  Languages.BULGARIAN: 'bg',
  Languages.CATALAN: 'ca',
  Languages.CZECH: 'cz',
  Languages.DANISH: 'da',
  Languages.GERMAN: 'de',
  Languages.GREEK: 'el',
  Languages.ENGLISH: 'en',
  Languages.BASQUE: 'eu',
  Languages.PERSIAN_FARSI: 'fa',
  Languages.FINNISH: 'fi',
  Languages.FRENCH: 'fr',
  Languages.GALICIAN: 'gl',
  Languages.HEBREW: 'he',
  Languages.HINDI: 'hi',
  Languages.CROATIAN: 'hr',
  Languages.HUNGARIAN: 'hu',
  Languages.INDONESIAN: 'id',
  Languages.ITALIAN: 'it',
  Languages.JAPANESE: 'ja',
  Languages.KOREAN: 'kr',
  Languages.LATVIAN: 'la',
  Languages.LITHUANIAN: 'lt',
  Languages.MACEDONIAN: 'mk',
  Languages.NORWEGIAN: 'no',
  Languages.DUTCH: 'nl',
  Languages.POLISH: 'pl',
  Languages.PORTUGUESE: 'pt',
  Languages.PORTUGUESE_BRAZIL: 'pt_br',
  Languages.ROMANIAN: 'ro',
  Languages.RUSSIAN: 'ru',
  Languages.SWEDISH: 'sv',
  Languages.SLOVAK: 'sk',
  Languages.SLOVENIAN: 'sl',
  Languages.SPANISH: 'sp',
  Languages.SERBIAN: 'sr',
  Languages.THAI: 'th',
  Languages.TURKISH: 'tr',
  Languages.UKRAINIAN: 'ua',
  Languages.VIETNAMESE: 'vi',
  Languages.CHINESE_SIMPLIFIED: 'zh_cn',
  Languages.CHINESE_TRADITIONAL: 'zh_tw',
  Languages.ZULU: 'zu',
};
